// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6LOu258CnlqGqtFlGAhy1h6YIuKdWoFs',
    appId: '1:816917690439:web:17c82c461b95659dc31962',
    messagingSenderId: '816917690439',
    projectId: 'dfuapp-a4401',
    authDomain: 'dfuapp-a4401.firebaseapp.com',
    storageBucket: 'dfuapp-a4401.firebasestorage.app',
    measurementId: 'G-MR5JW7N2BR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbC9U2nbgLmvlp87w_RWsEGPXUhecl21U',
    appId: '1:816917690439:android:0f9f0c9022fd22c3c31962',
    messagingSenderId: '816917690439',
    projectId: 'dfuapp-a4401',
    storageBucket: 'dfuapp-a4401.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsIyU8WKm7XRltuCDh6zCs460hq3cS7fA',
    appId: '1:816917690439:ios:f8e32c18979dcb4ec31962',
    messagingSenderId: '816917690439',
    projectId: 'dfuapp-a4401',
    storageBucket: 'dfuapp-a4401.firebasestorage.app',
    iosClientId: '816917690439-rimn5gpog4tagro5bt0uiuh1g3nnoi96.apps.googleusercontent.com',
    iosBundleId: 'com.dfu.healthcare.dfuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsIyU8WKm7XRltuCDh6zCs460hq3cS7fA',
    appId: '1:816917690439:ios:f8e32c18979dcb4ec31962',
    messagingSenderId: '816917690439',
    projectId: 'dfuapp-a4401',
    storageBucket: 'dfuapp-a4401.firebasestorage.app',
    iosClientId: '816917690439-rimn5gpog4tagro5bt0uiuh1g3nnoi96.apps.googleusercontent.com',
    iosBundleId: 'com.dfu.healthcare.dfuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6LOu258CnlqGqtFlGAhy1h6YIuKdWoFs',
    appId: '1:816917690439:web:38c128757742a632c31962',
    messagingSenderId: '816917690439',
    projectId: 'dfuapp-a4401',
    authDomain: 'dfuapp-a4401.firebaseapp.com',
    storageBucket: 'dfuapp-a4401.firebasestorage.app',
    measurementId: 'G-DNKGPTCPVT',
  );
}
